#define WS2812_DI_PIN D3
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 90
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_LED_COUNT 70
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#define RGB_MATRIX_SPLIT { 35, 35 }