#define WS2812_DI_PIN D3
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 90
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_LED_COUNT 70
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_SPLIT { 35, 35 } 
#define SPLIT_TRANSPORT_MIRROR